# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ala_id', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=30)),
                ('status', models.IntegerField(choices=[(0, 'APPLICANT'), (1, 'PROPOSED'), (2, 'ACCEPTED')])),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.TextField()),
                ('other_info', models.TextField()),
                ('memberships', models.TextField()),
                ('state', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=20)),
                ('notes', models.TextField()),
                ('form_date', models.DateField()),
                ('last_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
            },
        ),
    ]
