# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
        ('candidates', '0006_candidate_ala_appointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'APPLICANT'), (0, 'POTENTIAL'), (1, 'RECOMMENDED'), (2, 'ACCEPTED'), (2, 'DECLINED')])),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='desired_comms',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='potential_comms',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.Committee'),
        ),
    ]
