# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_auto_20160731_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(0, 'APPLICANT'), (0, 'POTENTIAL'), (1, 'RECOMMENDED'), (2, 'ACCEPTED'), (2, 'DECLINED')], default=0),
        ),
    ]
