# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_auto_20160731_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-form_date', 'last_updated'], 'verbose_name': 'Candidate', 'verbose_name_plural': 'Candidates'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Applicant'), (1, 'Potential'), (2, 'Recommended'), (3, 'Accepted'), (4, 'Declined')], default=0),
        ),
    ]
