# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_auto_20160731_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='candidates.Candidate'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='committees.Committee'),
        ),
    ]
