# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_auto_20160731_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Applicant', 'Applicant'), ('Potential', 'Potential'), ('Recommended', 'Recommended'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Applicant', max_length=12),
        ),
    ]
