# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_auto_20160731_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='locally_proposed',
            field=models.BooleanField(default=False, help_text='Set to True if the appointment was suggested by an Appointments Committee member - in this case you may have to ask the candidate to fill out a committee volunteer form, and also you should be careful of overwriting this.'),
        ),
    ]
