# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_appointment_locally_proposed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set([('candidate', 'committee')]),
        ),
    ]
