# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 14:07
from __future__ import unicode_literals

from django.db import migrations

def create_chairs_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    chairs = Group.objects.get_or_create(name='Chairs')

    # We can't add the can_appoint permission here, because permissions
    # specified in Meta are created on the post_migrate signal. Add permissions
    # in candidates/groups.py.


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0017_auto_20160805_1358'),
    ]

    operations = [
        migrations.RunPython(create_chairs_group),
    ]
