# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0020_auto_20160811_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='starred',
            field=models.BooleanField(default=False, help_text='Candidates that the chair wants the commmittee to pay particular attention to.'),
        ),
    ]
