# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0024_remove_candidate_review_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='library_type',
            field=models.IntegerField(choices=[(0, 'Public librarian'), (1, 'Academic librarian'), (2, 'School librarian'), (3, 'Special librarian'), (4, 'Student'), (5, 'Vendor'), (6, 'Other'), (7, 'Unknown')], default=7),
        ),
    ]
