# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0010_specify_committee_units'),
        ('candidates', '0025_candidate_library_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('privileged', models.BooleanField(help_text='Is this note written by someone with special authority over the appointments process, like an executive director or chair')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.Unit')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
