# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 20:30
from __future__ import unicode_literals

from django.db import migrations


def move_notes(apps, schema_editor):
    Note = apps.get_model('candidates', 'Note')
    Candidate = apps.get_model('candidates', 'Candidate')
    Unit = apps.get_model('committees', 'Unit')

    lita = Unit.objects.get(name='LITA')

    for candidate in Candidate.even_obsolete.all():
        if candidate.notes:
            note = Note()
            note.candidate = candidate
            note.unit = lita
            note.text = candidate.notes
            note.privileged = False
            note.save()

        if candidate.chair_notes:
            note = Note()
            note.candidate = candidate
            note.unit = lita
            note.text = candidate.chair_notes
            note.privileged = True
            note.save()


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0026_note'),
    ]

    operations = [
        migrations.RunPython(move_notes),
    ]
