# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0027_move_note_content_to_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='chair_notes',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='notes',
        ),
        migrations.AlterField(
            model_name='note',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='candidates.Candidate'),
        ),
        migrations.AlterField(
            model_name='note',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='committees.Unit'),
        ),
    ]
