# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0028_auto_20160921_1710'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set([('candidate', 'unit', 'privileged')]),
        ),
    ]
