# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 16:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0030_auto_20160921_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['form_date', 'committee'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelManagers(
            name='appointment',
            managers=[
                ('even_obsolete', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='form_date',
            field=models.DateField(default=datetime.datetime(2016, 9, 29, 16, 53, 27, 991629, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
