# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 16:54
from __future__ import unicode_literals

from django.db import migrations


def initialize_dates(apps, schema_editor):
    Appointment = apps.get_model('candidates', 'Appointment')
    for appt in Appointment.even_obsolete.all():
        # Assign date of candidate's most recent form to the appointment -
        # this is not necessarily right, but is not badly wrong. In particular,
        # this means we will be able to filter out any obsolete appointments.
        appt.form_date = appt.candidate.form_date
        appt.save()


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0031_auto_20160929_1653'),
    ]

    operations = [
        migrations.RunPython(initialize_dates),
    ]
