# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0033_remove_candidate_form_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'get_latest_by': 'form_date', 'ordering': ['form_date', 'committee'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
    ]
