# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-10 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0034_auto_20161017_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='_current_appointments',
            field=models.IntegerField(default=0),
        ),
    ]
