# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-10 00:25
from __future__ import unicode_literals

from django.db import migrations

def set_current_appointment_count(apps, schema_editor):
    Candidate = apps.get_model('candidates', 'Candidate')
    # Using 'objects' as the manager threw an error. Apparently it is not
    # serialized for use here.
    for candidate in Candidate._default_manager.all():
        candidate._current_appointments = candidate.appointments.filter(
            # For some reason it wasn't recognizing the Appointment named
            # constants here.
            status__in=['Sent',
                        'Recommended',
                        'Accepted']
            ).count()
        candidate.save()


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0035_candidate__current_appointments'),
    ]

    operations = [
        migrations.RunPython(set_current_appointment_count),
    ]
