# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-04 15:38
from __future__ import unicode_literals

from django.db import migrations

def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Appointment = apps.get_model('candidates', 'Appointment')
    for appt in Appointment.even_obsolete.filter(status='Accepted'):
        appt.year_start = 2016
        appt.year_end = 2018
        appt.save()

class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0037_auto_20170604_1531'),
    ]

    operations = [
    ]
