# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_committee_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='charge',
            field=models.URLField(blank=True, help_text='Link to committee charge', null=True),
        ),
        migrations.AddField(
            model_name='committee',
            name='notes',
            field=models.TextField(blank=True, help_text='Skills the committee is looking for, special requirements, etc.'),
        ),
    ]
