# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0004_auto_20160731_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
