# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0005_auto_20160801_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='short_code',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
