# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0008_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='committees.Unit'),
        ),
    ]
