# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 19:44
from __future__ import unicode_literals

from django.db import migrations

LITA_COMMS = ['LIT-ADVOC', 'LIT-CRM', 'LIT-ETHICS', 'JNT-META',
              'LIT-ADASSY', 'LIT-ARTF', 'LIT-BY', 'LIT-CHRIS', 'LIT-CCC',
              'LIT-CAM', 'LIT-ED', 'LIT-AWEND', 'LIT-FAC', 'LIT-FTRF',
              'LIT-IGCOORD', 'LIT-APPOINTS', 'LIT-DIVINCL', 'LIT-LOCALTF',
              'LIT-AWOCLCMN', 'LIT-AWHITECH', 'LIT-MB', 'LIT-NF17', 'LIT-NF18',
              'LIT-NM17', 'LIT-AWOCLCKIL', 'LIT-PG', 'LIT-PB', 'LIT-TTT',
              'LIT-WEBCOORD']


def add_units_to_committees(apps, schema_editor):
    # First, set up the unitial units.
    Unit = apps.get_model('committees', 'Unit')
    lita = Unit(name='LITA')
    lita.save()
    ala = Unit(name='ALA')
    ala.save()

    # Second, link LITA committees to LITA; any others belong to ALA.

    Committee = apps.get_model('committees', 'Committee')

    for comm in Committee.objects.all():
        if comm.short_code in LITA_COMMS:
            comm.unit = lita
        else:
            comm.unit = ala

        comm.save()


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0009_committee_unit'),
    ]

    operations = [
        migrations.RunPython(add_units_to_committees),
    ]
