# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0011_auto_20160919_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['name'], 'permissions': (('appointment__can_recommend', 'Can recommend appointments to unit committees'), ('appointment__can_finalize', 'Can finalize appointments to unit committees'), ('appointment__can_see', 'Can see (but not change) appointments to unit committees'), ('email__can_send', 'Can send email for unit-specific triggers'), ('note__can_make_candidate_note', 'Can make notes on candidates for unit committees'), ('note__can_make_privileged_note', 'Can make privileged notes on candidates for unit committees'), ('note__can_see', 'Can see (but not change) notes on candidates for unit committees')), 'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
    ]
