# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtype',
            options={'verbose_name': 'EmailType', 'verbose_name_plural': 'EmailTypes'},
        ),
    ]
