# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 19:57
from __future__ import unicode_literals

from django.db import migrations


def add_units_to_committees(apps, schema_editor):
    Unit = apps.get_model('committees', 'Unit')

    # This is guaranteed to exist, because this migration depends on
    # emails.0003, which in turn depends on committees.0010, which created
    # the LITA unit.
    lita = Unit.objects.get(name='LITA')

    EmailType = apps.get_model('emails', 'EmailType')
    for email in EmailType.objects.all():
        email.unit = lita
        email.save()


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20160915_1957'),
    ]

    operations = [
        migrations.RunPython(add_units_to_committees),
    ]
